### ISSUE TITLE
frostr+fedimint+nostr=🫂🤝

### ISSUE THREAD

**Issue by EthnTuttle** [nickfarrow/frostr#2]
Project status?

Interested in using this combined with a fedimint to do some weird things on nostr.
Please find me if interested in chatting about it: npub1tmycvul7aj4fxhypg5qkjgsjtx30zvnrfeufrgx9xlwtv0hne7cs67el78

**Comment by nickfarrow** [comment]
Haven't been working on this lately. But we do have frost nostr in https://github.com/frostsnap/frostsnap, though currently there is no way for two remote coordinators to interact (same problem here) and smoothly sign a message.

I suppose this could be done relatively easily with existing fedimint module infrastructure though!

**Comment by EthnTuttle** [comment]
yea. we already have DKG handled and then comms/coordination between signers. 

Thnx for the pointer to frostsnap, I'll give it a peek to see how it works.
